language: python

python: 3.7.1

branches: master

install:
    - pip install mkdocs mkdocs-material pymdown-extensions pygments

before_deploy:
    - mkdocs build --verbose --clean --strict

script:
    - echo "test"

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $github_token
    local_dir: docs
    on:
        branch: master
