site_name: 'Moo Docs'
site_description: 'Personal docs for random stuff'
site_author: 'Edy'
site_url: 'https://docs.edy.io'

docs_dir: mkdocs
site_dir: docs

nav:
  - Home: index.md
  - About: about.md
  - Linux:
    - Linux Basics: linux/linux-basics.md
    - Arch Linux Installation: linux/arch-linux-installation.md
    - Arch Linux Config: linux/arch-linux-config.md
    - zsh shell: linux/zsh-shell.md
  - Other:
    - DockerPlex: other/docker-plex.md
    - Google Analytics: other/google-analytics.md
  - Game Servers:
    - CubeWorld: game_servers/cubeworld.md
    - Garrys Mod: game_servers/gmod.md
    - Minecraft: game_servers/minecraft.md
    - CSGO: game_servers/csgo.md
theme:
  name: 'material'
  palette:
    primary: 'light blue'
    accent: 'blue'
  feature:
    tabs: true

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  social:
    - type: twitter
      link: https://twitter.com/EdyTheCow

google_analytics:
  - 'UA-121434074-1'
  - 'auto'